version: "3.9"
services:
  family-fleet:
    build: .
    container_name: family-fleet
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - BASE_URL=${BASE_URL:-http://localhost:8000}
      - TZ=${TZ:-America/Los_Angeles}
      - SQLITE_PATH=/data/app.db
      - OIDC_ISSUER=${OIDC_ISSUER}
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      - OIDC_REDIRECT_PATH=/auth/callback
      - OIDC_SCOPES=openid profile email
    volumes:
      - ./data:/data
